"""
Django settings for lms_project project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# ✅ Base directory
BASE_DIR = Path(__file__).resolve().parent.parent

# ✅ Secret key for development (DO NOT use in production)
SECRET_KEY = 'django-insecure-%*+&%!7=od!tsd2z^jdc15@-u7r(7y(y7x8$wvk^a*+@2-5@-v'

# ✅ Debug mode
DEBUG = True

# ✅ Allowed hosts (keep empty in development)
ALLOWED_HOSTS = []

# ✅ Installed apps (Django + Your apps)
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Your custom apps
    'books',
    'iam',
    'subscription',
]

# ✅ Middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ✅ Root URL configuration
ROOT_URLCONF = 'lms_project.urls'

# ✅ Templates settings
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # 👈 Global templates folder
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',  # 👈 Needed for login
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ✅ WSGI application
WSGI_APPLICATION = 'lms_project.wsgi.application'

# ✅ Database settings (SQLite by default)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ✅ Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ✅ Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# ✅ Static files (CSS, JS, etc.)
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static'  # 👉 You must create a folder named 'static'
]

# ✅ Media files (for user-uploaded images like profile photos)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'  # 👉 You must create a folder named 'media'

# ✅ Authentication redirects
LOGIN_URL = '/iam/login/'
LOGIN_REDIRECT_URL = '/iam/profile/'
LOGOUT_REDIRECT_URL = '/iam/login/'

# ✅ Default auto primary key field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
